website/auth.py
from flask import Blueprint,render_template, request, flash, redirect, url_for, current_app, session
from . import db
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Mail, Message
import random
import string
import requests

auth = Blueprint('auth', __name__)

# ----------------------------------------EMAIL VERIFICATION--------------------------------

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()    #   .first() Shows 1st result
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
                # return redirect(url_for('views.emailotp'))
                # return redirect(url_for('auth.emailotp',user=current_user))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)
    

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method == "POST":
        email = request.form.get('email')
        fname = request.form.get('fname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()    #   .first() Shows 1st result
        if user:
            flash('Email already exists.', category='error')
        else:
            if len(email) < 4:
                flash('Invalid Email', category='error')
            elif len(fname) < 2:
                flash('Name must be greater than 1 character', category='error')
            elif len(password1) < 7:
                flash('Password must be atleast 7 characters', category='error') 
            elif password1 != password2:
                flash('Passwords should match', category='error')
            else:
                new_user = User(email = email, fname = fname, password = generate_password_hash(password1, method='pbkdf2:sha256'))
                db.session.add(new_user)
                db.session.commit()
                # login_user(user, remember=True)
                flash('Account created!', category='success')
                return redirect(url_for('auth.login')) # or url_for('/')


    return render_template("sign_up.html", user=current_user)

# ----------------------------------------------------Email Route-------------------------------

@auth.route('/book_tickets', methods=['POST'])
def book_tickets():
    movie = request.form.get('movie')
    date = request.form.get('date')
    city = request.form.get('city')
    cinema = request.form.get('cinema')
    category = request.form.get('Category')
    ticketsnum = int(request.form.get('ticketsnum'))
    time = request.form.get('Time')
    
    # Determine price based on the category
    price_per_ticket = 0
    if category == "silver":
        price_per_ticket = 120
    elif category == "gold":
        price_per_ticket = 180
    elif category == "platinum":
        price_per_ticket = 240

    price = price_per_ticket * ticketsnum
    tax = 0.18*price
    total_payable = price + tax

    # Email message

    recipient_email = current_user.email

    msg = Message(
        'Your Ticket Booking Confirmation',
        sender='kabirjeet0370.becse24@chitkara.edu.in',
        recipients=[recipient_email]  
    )
    msg.body = f'''
    Movie: {movie}
    Show Date: {date}
    Show Time: {time}
    City: {city.capitalize()}
    Cinema: {cinema}
    Seat Category: {category.capitalize()}
    Number of Tickets: {ticketsnum}
    Price Per Ticket: Rs.{price_per_ticket}
    Total Amount Payable (Inc. all Taxes): Rs.{total_payable}
    '''
    
    # Send the email
    # mail.send(msg)
    
    # return 'Email sent!'

    mail = current_app.extensions.get('mail') 
    if mail:
        mail.send(msg)
        flash('Booking Confirmation Email Sent Successfully to registered email address!', category='success')
        return redirect(url_for('views.home')) # or url_for('/')
        # return 'Email sent!'
    else:
        flash('Email service is not configured properly.', category='error')
        return redirect(url_for('auth.book_tickets'))
    
# ------------------------------------------------------Reset Password------------------------------------------

def generate_otp():
    return ''.join(random.choices(string.digits, k=6))

@auth.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if request.method == 'POST':
        email = request.form.get('email')
        otp = request.form.get('otp')
        new_password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')

        if email and not otp and not new_password:
            user = User.query.filter_by(email=email).first()
            if user:
                generated_otp = generate_otp()
                session['otp'] = generated_otp
                session['otp_email'] = email

                msg = Message(
                    'Your OTP for Password Reset',
                    sender='kabirjeet0370.becse24@chitkara.edu.in',
                    recipients=[email]
                )
                msg.body = f"Your OTP is: {generated_otp}"
                mail = current_app.extensions.get('mail')
                if mail:
                    mail.send(msg)
                    flash('OTP sent to your email. Please enter the OTP to proceed.', category='success')
                    return render_template("reset_password.html", email=email, show_otp_field=True, user=current_user)
                else:
                    flash('Email service is not configured properly.', category='error')
            else:
                flash('Email does not exist.', category='error')

        elif email and otp and not new_password:
            if otp == session.get('otp') and email == session.get('otp_email'):
                flash('OTP verified! You can now reset your password.', category='success')
                return render_template("reset_password.html", email=email, show_password_fields=True, user=current_user)
            else:
                flash('Invalid OTP. Please try again.', category='error')
                return render_template("reset_password.html", email=email, show_otp_field=True, user=current_user)

        elif email and new_password and confirm_password:
            if new_password == confirm_password and len(new_password) >= 7:
                user = User.query.filter_by(email=email).first()
                if user:
                    user.password = generate_password_hash(new_password, method='pbkdf2:sha256')
                    db.session.commit()
                    session.pop('otp', None)
                    session.pop('otp_email', None)
                    flash('Password reset successfully!', category='success')
                    return redirect(url_for('auth.login'))
                else:
                    flash('An error occurred. Please try again.', category='error')
            else:
                flash('Passwords do not match or are too short.', category='error')

    return render_template("reset_password.html", show_otp_field=False, show_password_fields=False, user=current_user)

# ----------------------------------------------------------Search Movie--------------------------------------------

@auth.route('/search_movies', methods=['GET'])
def search_movies():
    query = request.args.get('query')
    api_key = "44905570c15e2962f494748d812e8a95"
    url = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&query={query}"

    response = requests.get(url)
    if response.status_code == 200:
        movies = response.json().get('results', [])
    else:
        movies = []
        flash("Failed to fetch movie results. Try again later.", "error")

    for movie in movies:
        movie['poster_url'] = f"https://image.tmdb.org/t/p/w200{movie['poster_path']}" if movie.get('poster_path') else None

    return render_template('search_results.html', movies=movies, user=current_user)


# ------------------------------------------------------English Routes----------------------------------------------

@auth.route('/bookfastandfurious')
def bookfastandfurious():
    return render_template("bookfastandfurious.html", user=current_user)

@auth.route('/bookprey')
def bookprey():
    return render_template("bookprey.html", user=current_user)

# -------------------------------------------------------Hindi Routes-----------------------------------------------

@auth.route('/bookarticle370')
def bookarticle370():
    return render_template("bookarticle370.html", user=current_user)

@auth.route('/bookWelcomeToJungle')
def bookWelcomeToJungle():
    return render_template("bookWelcomeToJungle.html", user=current_user)

@auth.route('/bookBabyJohn')
def bookBabyJohn():
    return render_template("bookBabyJohn.html", user=current_user)

@auth.route('/bookchhaava')
def bookchhaava():
    return render_template("bookchhaava.html", user=current_user)

@auth.route('/bookKesari2')
def bookKesari2():
    return render_template("bookKesari2.html", user=current_user)

# -------------------------------------------------------Punjabi Routes----------------------------------------------

@auth.route('/bookjattandjuliet3')
def bookjattandjuliet3():
    return render_template("bookjattandjuliet3.html", user=current_user)

@auth.route('/bookardaas_sdbd')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="static/camera_icon.png" type="image/x-icon">
    <link rel="stylesheet" href="static/CSS/base.css">

    <style>
        .wrapper {
            min-height: 100vh;
            width: 100%;
            /* background-image: url("static/Webimg/BookMySpot_Backgroundimg.png"); */
            background-image: url("static/Webimg/BMS_Background.png");
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
            /* opacity: 0.5; */
        }

        a:hover{
            text-decoration: none;
        }

        .container {
            padding-top: 20px;
            background-color: rgba(230, 230, 230, 0.7);
            min-height: 100vh;
            padding-bottom: 100px;
        }

        @media(max-width: 430px){
            .wrapper{
                max-width: 100vh;
            }
            .navigationbar{
                max-width: 100vh;
            }
        }
    </style>
    <title>{% block title %}Home{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark navigationbar">
        <a href="/"><img src="static/Webimg/BookMySpot.png" alt="BookMySpot" width="100px" height="60px"></a>
        <a href="/"><h2 class="text-white ps-3">BookMySpot</h2></a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"><i class="fa-solid fa-bars" style="color: white;"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav ml-auto">
                <form class="form-inline my-2 my-lg-0" action="{{ url_for('auth.search_movies') }}" method="GET">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search movies" aria-label="Search" name="query" required>
                    <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
                </form>
                {% if user.is_authenticated %}
                <h6 style="color: white;" class="nav-item nav-link">Welcome {{user.fname}},</h6>
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="wrapper">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% if message == "Please log in to access this page." %}
        <div class="message alert alert-danger alert-dismissable fade show" role="alert">{{ message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        {% if category == 'error' %}
        <div class="message alert alert-danger alert-dismissable fade show" role="alert">{{ message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissable fade show" role="alert">{{ message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

        <script>
            setTimeout(function() {
                var alert = document.querySelector('.alert'); 
                if (alert) {
                    alert.classList.remove('show');  
                    alert.classList.add('fade');
                    setTimeout(function() {
                        alert.style.display = 'none';  
                    }, 500);  
                }
            }, 5000); 
        </script>
</body>

</html>

website/templates/bookKesari2.html
{% extends "base.html" %}
{% block title %}Book Article 370{% endblock %}

{% block content %}

<div class="container my-5">
    <!-- Movie Poster and Trailer Section -->
    <div class="row movie text-center">
        <div class="col-lg-4 col-md-6 col-sm-12 mb-3 d-flex justify-content-center align-items-center">
            <img src="static/Bollywood_Poster/Bollywood_Poster_Kesari2.jpeg" alt="Kesari2 Movie Poster" class="img-fluid" style="max-height: 300px; height: auto;">
        </div>
        <div class="col-lg-8 col-md-6 col-sm-12 mb-3">
            <video src="static/Bollywood_Poster/Kesari2_Trailer.mp4" class="w-100" style="height: 300px;" muted autoplay controls></video>
        </div>
    </div>

    <!-- Booking Options Section -->
    <div class="row">
        <div class="col-12">
            <form action="/book_tickets" method="post">
                <input type="checkbox" name="movie" id="movie" value="Srikanth" checked hidden>

                <!-- City selection -->
                <div class="form-group text-center">
                    <label for="city" class="font-weight-bold">Select Your City:</label>
                    <select name="city" id="city" class="form-control" onchange="cinemalogic()">
                        <option value="">Select Your City</option>
                        <option value="rajpura">Rajpura</option>
                        <option value="chandigarh">Chandigarh</option>
                        <option value="mohali">Mohali</option>
                        <option value="ambala">Ambala</option>
                    </select>
                </div>

                <!-- Cinema selection for each city -->
                <div class="form-group text-center" id="rjp" style="display: none;">
                    <label for="cinema" class="font-weight-bold">Select Your Preferred Cinema:</label>
                    <select name="cinema" class="form-control">
                        <option value=" ">Select a Cinema</option>
                        <option value="Prime Hub">Prime Hub</option>
                    </select>
                </div>

                <div class="form-group text-center" id="chd" style="display: none;">
                    <label for="cinema" class="font-weight-bold">Select Your Preferred Cinema:</label>
                    <select name="cinema" class="form-control">
                        <option value=" ">Select a Cinema</option>
                        <option value="PVR Elante">PVR Elante</option>
                        <option value="PVR Centra">PVR Centra</option>
                    </select>
                </div>

                <div class="form-group text-center" id="moh" style="display: none;">
                    <label for="cinema" class="font-weight-bold">Select Your Preferred Cinema:</label>
                    <select name="cinema" class="form-control">
                        <option value=" ">Select a Cinema</option>
                        <option value="PVR CP67">PVR CP67</option>
                        <option value="PVR VR Punjab">PVR VR Punjab</option>
                        <option value="PVR Mohali Walk">PVR Mohali Walk</option>
                    </select>
                </div>

                <div class="form-group text-center" id="amb" style="display: none;">
                    <label for="cinema" class="font-weight-bold">Select Your Preferred Cinema:</label>
                    <select name="cinema" class="form-control">
                        <option value=" ">Select a Cinema</option>
                        <option value="Fun Galaxy">Fun Galaxy</option>
                        <option value="Aryaan Cinema">Aryaan Cinema</option>
                    </select>
                </div>

                <!-- Seat category selection -->
                <div class="form-group text-center" id="seat_category" style="display: none;">
                    <label for="Category" class="font-weight-bold">Select the Category of Seats:</label>
                    <select name="Category" id="Category" class="form-control">
                        <option value=" ">Select your Category</option>
                        <option value="silver">Silver - Rs.120</option>
                        <option value="gold">Gold - Rs.180</option>
                        <option value="platinum">Platinum - Rs.240</option>
                    </select>
                </div>

                <!-- Number of tickets selection -->
                <div class="form-group text-center" id="num_of_tickets" style="display: none;">
                    <label for="ticketsnum" class="font-weight-bold">Select Number of Tickets:</label>
                    <select name="ticketsnum" id="ticketsnum" class="form-control">
                        <option value=" ">Select Number of Tickets</option>
                        {% for i in range(1, 21) %}
                        <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <!-- Date selection -->
                <div class="form-group" id="movie_date" style="display: none;">
                    <label for="movie_date">Select Date:</label>
                    <input type="date" id="date" name="date" class="form-control" min="2024-11-01" max="2024-11-15">
                </div>

                <!-- Show time selection -->
                <div class="form-group text-center" id="movie_time" style="display: none;">
                    <label for="movie_time" class="font-weight-bold">Select Show Time:</label>
                    <select name="Time" id="time" class="form-control" onchange="check()">
                        <option value=" ">Select Your Preferred Slot</option>
                        <option value="09:00 A.M.">09:00 A.M.</option>
                        <option value="12:00 P.M.">12:00 P.M.</option>
                        <option value="03:00 P.M.">03:00 P.M.</option>
                        <option value="06:00 P.M.">06:00 P.M.</option>
                        <option value="09:00 P.M.">09:00 P.M.</option>
                    </select>
                </div>

                <!-- Book tickets button -->
                <button type="submit" class="btn btn-primary btn-block" id="bookbtn" style="display: none;">Book Tickets</button>
            </form>
        </div>
    </div>
</div>

<!-- JavaScript -->
<script>
    function cinemalogic() {
        var city = document.getElementById("city").value;
        const rjp = document.getElementById("rjp");
        const moh = document.getElementById("moh");
        const chd = document.getElementById("chd");
        const amb = document.getElementById("amb");
        const seat_category = document.getElementById("seat_category");
        const num_of_tickets = document.getElementById("num_of_tickets");
        const movie_date = document.getElementById("movie_date");
        const movie_time = document.getElementById("movie_time");

        rjp.style.display = city == 'rajpura' ? 'block' : 'none';
        chd.style.display = city == 'chandigarh' ? 'block' : 'none';
        moh.style.display = city == 'mohali' ? 'block' : 'none';
        amb.style.display = city == 'ambala' ? 'block' : 'none';

        if (city) {
            seat_category.style.display = 'block';
            num_of_tickets.style.display = 'block';
            movie_date.style.display = 'block';
            movie_time.style.display = 'block';
        }
    }

    function check() {
        var seat_category_val = document.getElementById("Category").value;
        var num_of_tickets_val = document.getElementById("ticketsnum").value;
        var timeslot_val = document.getElementById("time").value;

        document.getElementById("bookbtn").style.display = (seat_category_val && num_of_tickets_val && timeslot_val) ? 'block' : 'none';
    }
</script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}

<style>
    .forgotpass {
        margin-left: 89%;
    }

    @media(max-width: 950px) {
        .forgotpass {
            margin-left: 83%;
        }
    }

    @media(max-width: 850px) {
        .forgotpass {
            margin-left: 83%;
        }
    }

    @media(max-width: 550px) {
        .forgotpass {
            margin-left: 77%;
        }
    }

    @media(max-width: 430px) {
        .forgotpass {
            margin-left: 69%;
        }
    }

    @media(max-width: 400px) {
        .forgotpass {
            margin-left: 65%;
        }
    }

    @media(max-width: 350px) {
        .forgotpass {
            margin-left: 62%;
        }
    }
</style>

<form method="post">
    <h2 align="center" style="font-weight: bold;">Login</h2>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" id="email" placeholder="abc@xyz.com">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
        <input type="checkbox" id="showPassword" style="margin-top: 10px;">
        <label for="showPassword">Show Password</label> <br>
        <u><a href="{{ url_for('auth.reset_password') }}" class="forgotpass">Forgot Password?</a></u> <br>
    </div>
    <br>
    <center>
        <u>Don't have an account? <a href="/sign-up">sign-up Here</a></u> <br>
        <button type="submit" class="btn btn-primary">Login</button>
    </center>
</form>
<script>
    document.getElementById('showPassword').addEventListener('change', function () {
        const passwordField = document.getElementById('password');
        if (this.checked) {
            passwordField.type = 'text'; 
        } else {
            passwordField.type = 'password';
        }
    });
</script>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %} 
<form method="post">
    <h2 align="center"style="font-weight: bold;">Sign Up</h2>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" id="email" placeholder="abc@xyz.com">
    </div>
    <div class="form-group">
        <label for="fname">Name</label>
        <input type="text" class="form-control" name="fname" id="fname" placeholder="Enter your name">
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" name="password1" id="password1" placeholder="Enter Password">
    </div>
    <div class="form-group">
        <input type="checkbox" id="showPassword" style="margin-top: 10px;">
        <label for="showPassword">Show Password</label>
    </div>
    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm Password">
    </div>
    <br>
    <center>
        <u>Already have an account? <a href="/login">login Here</a></u> <br>
        <button type="submit" class="btn btn-primary">Create Account</button>
    </center>
</form>

<script>
    document.getElementById('showPassword').addEventListener('change', function () {
        const passwordField = document.getElementById('password1');
        if (this.checked) {
            passwordField.type = 'text'; 
        } else {
            passwordField.type = 'password';
        }
    });
</script>
{% endblock %}

website/templates/upcominghousefull5.html
{% extends "base.html" %} 
{% block title %}Housefull 5{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row movie text-center">
        <div class="col-lg-4 col-md-6 col-sm-12 mb-3 d-flex justify-content-center align-items-center">
            <img src="static/Upcoming/houseful 5.jpeg" alt="Punjab'95 Movie Poster" class="img-fluid" style="max-height: 300px; height: auto;">
        </div>
        <div class="col-lg-8 col-md-6 col-sm-12 mb-3">
            <video src="static/Upcoming/housefull 5_Trailer.mp4" class="w-100" style="height: 300px;" muted autoplay controls></video>
        </div>
    </div>

<h1>Storyline</h1>
<p>The plot of "Housefull 5" is centered around the reincarnation of a group of characters from the previous four films, "Housefull", "Housefull 2", "Housefull 3", and "Housefull 4". In this reincarnation-based comedy, the characters find themselves in new bodies, but still entangled with each other in a comedic, chaotic, and hilarious manner. The movie explores themes of fate, destiny, and the pursuit of love and happiness in a new life, with the familiar quirky characters from the previous installments navigating the modern era with their unique perspectives.</p>

<h1>Cast</h1>
<ul>
    <li>Akshay Kumar</li>
    <li>Chitrangda Singh</li>
    <li>Sanjay Dutt</li>
    <li>Jacqueline Fernandez</li>
    <li>Abhishek Bachchan</li>
    <li>Nargis Fakhri</li>
    <li>Jackie Shroff - Abhishek Bachchan's Father</li>
    <li>Riteish Deshmukh</li>
    <li>Nana Patekar</li>
    <li>Nikitin Dheer</li>
    <li>Sonam Bajwa</li>
    <li>Johny Lever - (as Johnny Lever)</li>
    <li>Dino Morea</li>
    <li>Fardeen Khan</li>
    <li>Shreyas Talpade</li>
    <li>Chunky Pandey</li>
    <li>Ranjeet Bedi - Akshay Kumar's Father</li>
    <li>Natalia Janoszek</li>
    <li>Archana Puran Singh</li>
    <li>Archana Puran Singh - Cameo</li>
    <li>Soundarya Sharma - Cameo</li>
    <li>Akashdeep Sabir - Doctor</li>
</ul>

{% endblock %}

website/templates/upcomingraid2.html
{% extends "base.html" %} 
{% block title %}Raid 2{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row movie text-center">
        <div class="col-lg-4 col-md-6 col-sm-12 mb-3 d-flex justify-content-center align-items-center">
            <img src="static/Upcoming/Raid2.jpeg" alt="Raid 2 Movie Poster" class="img-fluid" style="max-height: 300px; height: auto;">
        </div>
        <div class="col-lg-8 col-md-6 col-sm-12 mb-3">
            <video src="static/Upcoming/Raid2_Trailer.mp4" class="w-100" style="height: 300px;" muted autoplay controls></video>
        </div>
    </div>

<h1>Storyline</h1>
<p>Raid 2 is an upcoming Indian Hindi-language crime thriller film directed by Raj Kumar Gupta. The film is a sequel to Raid (2018) and stars Ajay Devgn, Riteish Deshmukh and Vaani Kapoor. Raid 2 follows the return of IRS officer Amay Patnaik (Devgn), who tracks another white-collar crime.

    Like the previous film, the sequel is also based on the income-tax raid conducted by the officers of Income Tax Department who work with intelligence agencies to track white-collar crimes. The film was announced in April 2020. Filming was held in Mumbai, Rajasthan, Uttar Pradesh, and Delhi in the first half of 2024.</p>

<h1>Cast</h1>
<ul>
    <li>Ajay Devgn</li>
    <li>Amay Patnaik</li>
    <li>Tamannaah Bhatia</li>
    <li>Vaani Kapoor</li>
    <li>Riteish Deshmukh</li>
    <li>Rajat Kapoor</li>
    <li>Neeta Satnani</li>
    <li>Receptionist</li>
    <li>Shruti Pandey</li>
    <li>Geeta Devi</li>
    <li>Madhvendra Jha</li>
    <li>Vishal Mishra</li>
    <li>Ayushi Nema</li>
    <li>Anita</li>
    <li>Sushil Dahiya</li>
    <li>Chief Minister</li>
    <li>Bhavna Singh Chauhan</li>
    <li>Vikram Pratap</li>
    <li>Srivastava Pritisha</li>
    <li>Mini</li>
    <li>Ashish Gokhale</li>
    <li>Rukh Nabeel</li>
    <li>Bhavna Mishra</li>
    <li>Sandeep Kapoor</li>
    <li>Puneet Sahni(credit only)</li>
    <li>Durgesh Chauhan</li>
    <li>Bhola driver</li>
    <li>Brij Bhushan Shukla</li>
  </ul>
    
{% endblock %}